# Generated by Django 4.2.7 on 2023-12-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_body_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('date', models.DateField(null=True)),
                ('image', models.ImageField(default='defaul.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
